import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import BootstrapClient from '@/components/BootstrapClient.js';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        {children}
        <BootstrapClient />
        </body>
    </html>
  )
}
